logout:
  pattern:   /logout

login_check:
  pattern:   /login_check
  
content:
    resource: "@SfbyStaticBundle/Controller/ContentController.php"
    type:     annotation

category:
    resource: "@SfbyStaticBundle/Controller/CategoryController.php"
    type:     annotation

product:
    resource: "@SfbyStaticBundle/Controller/ProductController.php"
    type:     annotation