imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: 'v1' }
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        disqus_public_key: %disqus_public_key%
    form:
        resources:
            - ::form.html.twig

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Sfby\UserBundle\Entity\User
    registration:
        form:
            type: sfby_user_registration
    profile:
        form:
            type: sfby_user_profile
            
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
    
avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: cache
    #one of the three drivers: `gd`, `imagick`, `gmagick`
    driver:       gd 
    filters:
        profile_avatar:
            #The `mode` can be either `outbound` or `inset`.
            type:    thumbnail
            options: { size: [99, 83], mode: outbound }            
        profile_form_avatar:
            type:    thumbnail
            options: { size: [25, 25], mode: outbound }
        profile_list_avatar:
            type:    thumbnail
            options: { size: [23, 23], mode: outbound }
            
sonata_admin:
    dashboard_groups:
        sfby_blog: 
            label: Blog
            items: ~
        sfby_user: 
            label: Users
            items: ~

knp_markdown:
    parser:
        service: markdown.parser.sfby