admin1:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


SfbyDefaultBundle:
    resource: "@SfbyDefaultBundle/Controller/"
    type:     annotation
    
SfbyUserBundle:
    resource: "@SfbyUserBundle/Controller/"
    type:     annotation
    prefix:   /user

SfbyBlogBundle:
    resource: "@SfbyBlogBundle/Controller/"
    type:     annotation
    prefix:   /blogs

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

_imagine:
    resource: .
    type:     imagine

_security_logout:
    pattern:  /logout


# This is defined for facebook login authentication,
# a controller is associated with it but does nothing
_security_check_facebook:
    pattern: /login_check/facebook
    defaults: { _controller: SfbyUserBundle:Default:checkFacebook }
