<?php

namespace Sfby\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findForCloud()
    {
        $res = $this->getEntityManager()
            ->createQuery('SELECT t, count(b.id) FROM SfbyBlogBundle:Tag t LEFT JOIN t.blogs b GROUP BY t.id')
            ->getResult();
        
        $groups = 3;
        $min = 9999;
        $max = 0;
        foreach ($res as $arr)
        {
            $min = $arr[1] < $min ? $arr[1] : $min;
            $max = $arr[1] > $max ? $arr[1] : $max;
        }
        
        $s = ($max - $min)/$groups;
        foreach ($res as $i => $arr)
        {
            $group = round(($arr[1]-$min)/$s);
            $res[$i][1] = $group;
        }
        
        return $res;
    }
}