parameters:
#    sfby_static.example.class: Sfby\DefaultBundle\Example

services:
#    sfby_static.example:
#        class: %sfby_static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
